from files.interview_app.long_text_Java import java
from files.interview_app.long_text_JVM import jvm
from files.interview_app.long_text_Jmt import jmt
from files.interview_app.long_text_CNet import cnet
from files.interview_app.long_text_OS import os
from files.interview_app.long_text_DM import dm
from files.interview_app.long_text_Ds_Al import ds_al
from files.interview_app.long_text_Mysql import mysql
from files.interview_app.long_text_Redis import redis
